### ISSUE TITLE
Passing API response into Table

### ISSUE THREAD

**Issue by tylercrosse** [ga-wdi-exercises/project2#329]
I'm trying to get values from a JSON provided by the gihub api and store them as values in my table.

I've been trying to do it using HTTParty because that makes a little more sense to me than using the dedicated github api gem Octokit.

In trying to debug/learn what is going on I've been trying to break this down in the rails console by passing  HTTParty the url for my repos - https://api.github.com/users/tylercrosse/repos . I was then going to try to get the info from the first repo to practice then once I get that figured out iterate over the whole JSON to create table entries for each repo for the specified user.

The problem is that HTTParty hangs when I try to do a .get in the rails console. I've included what I've been working on in my class so far and the error message I get when I ^C out of the rails console.

One thought is that maybe I needed to somehow be authenticated to receive a response? It's just weird that there isn't a spot to put in a key or token and that I can go to the request address (the link above) and it displays a big JSON.

I'm also not opposed to suggestions on a better way to do this if there is one. Thanks!

Ruby:

``` ruby
class LocalizeRepo

  # initialize method take arguments
  def initialize()

    url = "https://api.github.com/users/#{current_user.nickname}/repos"

    # utilizing httparty gem to make get request to the url prescribed in the
    # line above and storing the response into the variable below.
    response = HTTParty.get(url)

    Repo.create(
      rid: response[0][:id],
      name: response[0][:name],
      full_name: response[0][:full_name],
      user_id: current_user.id,
      html_url: response[0][:html_url],
      description: response[0][:description],
      owner: response[0][:owner][:login],
      owner_avatar_url: response[0][:owner][:avatar_url],
      owner_html_url: response[0][:owner][:html_url]
    )
  end
end
```

Console Error messages - also doing `$ spring stop` didn't help

```
> response = HTTParty.get(url)
^CIRB::Abort: abort then interrupt!
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `call'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.5/lib/httparty/request.rb:101:in `perform'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.5/lib/httparty.rb:460:in `get'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/httparty-0.13.5/lib/httparty.rb:560:in `get'
    from (irb):3
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
... 8 levels...
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/commands/rails.rb:6:in `call'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/command_wrapper.rb:38:in `call'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application.rb:183:in `block in serve'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application.rb:156:in `fork'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application.rb:156:in `serve'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application.rb:131:in `block in run'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application.rb:125:in `loop'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application.rb:125:in `run'
    from /Users/tyliewylie/.rvm/gems/ruby-2.2.3/gems/spring-1.4.1/lib/spring/application/boot.rb:18:in `<top (required)>'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/tyliewylie/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by RobertAKARobin** [comment]
Huh. That's weird. It worked just fine for me. Has it worked yet for you?

**Comment by tylercrosse** [comment]
Ugh. Haha well it didn't work for the last ~hour but it works now. Is doing that Repo.create and passing it details for each repo entry and then trying to iterate over an ok way of getting the info into my DB?

**Comment by RobertAKARobin** [comment]
Sure that's fine. I think you may be running into the Github API's rate limits: you can only query the API `x` number of times before it starts rejecting you. There are ways you can authorize your app to prevent this from happening.

**Comment by tylercrosse** [comment]
Ok cool, thanks! I've got the login through Omniauth but it looks like I need to do a little more to authenticate each request. I'll keep playing with it.

Also Gringotts is cool! I wish I could figure out exactly what all of it does.

**Comment by RobertAKARobin** [comment]
It's literally just a glorified version of `https://github.com/ga-dc`. We didn't like the filtering on that, so we made this one.
