### ISSUE TITLE
many 2 many still have issues

### ISSUE THREAD

**Issue by merubin** [ga-wdi-exercises/project2#695]
Still cannot get the seed to work.
Here is the latest ERD
![image](https://cloud.githubusercontent.com/assets/19254862/19405343/91f0ac9e-9244-11e6-8730-c5b07d864cdc.png)

```
$ rails db:seed
rails aborted!
NoMethodError: undefined method `portfolios' for #<User:0x007fee91d7cdc8>
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activemodel-5.0.0.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/MICHAELS_MAC/wdi/projects/project2/portfolio_management_system/db/seeds.rb:85:in `<top (required)>'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `block in load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:287:in `load'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:549:in `load_seed'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/tasks/database_tasks.rb:268:in `load_seed'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/activerecord-5.0.0.1/lib/active_record/railties/databases.rake:196:in `block (2 levels) in <top (required)>'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:13:in `block in run_rake_task'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/Users/MICHAELS_MAC/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
  Fri Oct 14 19:30:08 ~/wdi/projects/project2/portfolio_management_system (master)
$
```

[latest code](https://github.com/merubin/portfolio_management_system) has been pushed to github

**Comment by merubin** [comment]
I can successfully create users and projects with this:

```
user1 = User.create!({
  name: "Mike Rubin",
  userid: "merubin",
  password: "password",
  email:"mike@rubinsworld.com",
  avatar_url:"http://mike-rubin.com/images/nav/id/rubin_selfie_270.png"
})

project1 = user1.projects.create!({
name:"Mario's Match Game",
header1:"Javascript Project",
header2:"",
description:"Pre-work project for WDI-DC12 Bootcamp. Concentration like game where random cards are displayed and flipped as user choices. This work includes CSS, HTML5 along with Javascript and dynamic DOM manulipuation.
Bonus work to keep score and win and loss was done.",
screen_img_url:"http://mike-rubin.com/images/portfolio/mariomemorygame.jpg",
host_url:"http://www.rubinsworld.com/ga/memory/index.html"
})
```

If I try to create a portfolio  with this:

```
portfolio1 = project1.portfolios.create!({
title:"Mike Rubin's Personal Portfolio",
description:"Welcome to Mike Rubin's Web Development Portfolio. "
})
```

I get this error:
**$ rails db:seed
rails aborted!
ActiveRecord::RecordInvalid: Validation failed: User must exist**

Do I need to somehow create the ProjectsPortfio record first and seed the userid?  if so how?

Thanks,

Mike

**Comment by merubin** [comment]
I woke up this morning and looked at what I was trying to do.  
left out a has_many :projects in the users model (UGH..)  Sleep is a wonderful thing!

Case Closed!
